spring:
  application:
    name: dwsc-player
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
    openfeign:
      client:
        config:
          dwsc-comment:
            url: ${COMMENT_SERVICE_URL:}
  config:
    import: "optional:configserver:"

corba:
  news:
    host: ${CORBA_NEWS_HOST:127.0.0.1}
    port: ${CORBA_NEWS_PORT:1050}
    serviceName: ${CORBA_NEWS_SERVICE_NAME:NewsService}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

