spring:
  application:
    name: dwsc-player
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

