spring:
  application:
    name: dwsc-comment
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
    openfeign:
      client:
        config:
          dwsc-player:
            url: ${PLAYER_SERVICE_URL:}
  config:
    import: "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

