server:
  port: ${PORT:8888}
  forward-headers-strategy: framework

spring:
  application:
    name: dwsc-config
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:file:../config-repo}

  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443

